services:
  app:
    container_name: app
    hostname: app
    network_mode: host
    image: maven:3-openjdk-17
    volumes:
      - ./:/usr/src/mymaven:ro
    working_dir: /usr/src/mymaven
    entrypoint: "/bin/bash"
    command:
      ["-c", "mvn exec:java -Dexec.mainClass=ufpa.labsd.zookeeper.Corrida"]
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: bitnami/zookeeper:3.6.2
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  zoonavigator:
    container_name: zoonavigator
    image: elkozmon/zoonavigator:1.1.3
    ports:
      - 9000:9000
