services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: bitnami/zookeeper:3.6.2
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  zoonavigator:
    container_name: zoonavigator
    image: elkozmon/zoonavigator:1.1.3
    ports:
      - 9000:9000
